dist: xenial
language: minimal
service: docker

install:
    - docker pull keyiz/garnet-flow
    - docker run -d -it --name lassen keyiz/garnet-flow bash
    - docker cp ../lassen lassen:/
    - docker exec -i lassen bash -c "pip install -r /lassen/requirements.txt" 
    - docker exec -i lassen bash -c "pip install pytest python-coveralls"
    - docker exec -i lassen bash -c "pip install pytest-cov pytest-codestyle" 
    # check CoSA dependencies
    - docker exec -i lassen bash -c "pysmt-install --check"
    - docker exec -i lassen bash -c "cd /lassen && pip install -e ." 
    
script:
    - docker exec -i lassen bash -c "/lassen/.travis/run.sh"

