language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - verilator    
before_install:
# install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7
- source activate test-env
- conda install pip
install:
- pip install pysmt
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.6:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.6:${LD_LIBRARY_PATH}"
- pysmt-install --check
- pip install pytest-cov
- git clone https://github.com/phanrahan/peak.git
- git clone -b iofix https://github.com/rdaly525/MetaMapper.git
- pip install --ignore-installed git+git://github.com/leonardt/fault#egg=fault
- pip install --ignore-installed git+git://github.com/phanrahan/magma#egg=magma-lang
- pip install --ignore-installed git+git://github.com/phanrahan/mantle#egg=mantle
- pip install -e ./peak
- pip install -e ./MetaMapper
- pip install -e .
script:
- pytest -x tests/
