dist: xenial
language: python
python:
- 3.7
cache:
  apt: true
addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - verilator
install:
- pip install coreir
- pip install -r requirements.txt
- pip install pytest-cov
- pip install python-coveralls
- pip install -e .
script:
- ./.travis/run.sh
after_success:
- coveralls
